### ISSUE TITLE
Simulation crashed

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#320]
Schon mehrmals aufgetreten, kann es aber nicht wirklich reproduzieren. Float Ungenauigkeit?

```
Exception in thread "Timer-0" java.lang.IllegalArgumentException: The temperature of a liquid in Kelvin needs to be <= 503.15
	at edu.kit.pse.osip.core.model.base.Liquid.<init>(Liquid.java:34)
	at edu.kit.pse.osip.core.model.simulation.SubtractiveMixingStrategy.mixLiquids(SubtractiveMixingStrategy.java:57)
	at edu.kit.pse.osip.core.model.simulation.MixTankSimulation.putIn(MixTankSimulation.java:35)
	at edu.kit.pse.osip.simulation.controller.PhysicsSimulator.tick(PhysicsSimulator.java:39)
	at edu.kit.pse.osip.simulation.controller.SimulationController$1.run(SimulationController.java:172)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by ByteHamster** [comment]
Klickt man "reset" wird eine abgestürzte Simulation nicht wieder gestartet
