### ISSUE TITLE
Zahlen auf der Ausgabe

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#417]
Ich habe es geschafft, einen Stacktrace zu bekommen, während die Zahlen geloggt werden

```
"JavaFX Application Thread@806" prio=5 tid=0x10 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at edu.kit.pse.osip.monitoring.view.dashboard.UIOutputStream.print(UIOutputStream.java:154)
	  - locked <0xb9f> (a edu.kit.pse.osip.monitoring.view.dashboard.UIOutputStream)
	  at edu.kit.pse.osip.monitoring.view.dashboard.UIOutputStream.print(UIOutputStream.java:139)
	  at edu.kit.pse.osip.monitoring.view.dashboard.UIOutputStream.write(UIOutputStream.java:40)
	  at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	  at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	  at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
	  at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	  - locked <0xd1e> (a java.io.OutputStreamWriter)
	  at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	  at java.util.logging.StreamHandler.flush(StreamHandler.java:259)
	  - locked <0xd1f> (a java.util.logging.ConsoleHandler)
	  at java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:117)
	  at java.util.logging.Logger.log(Logger.java:738)
	  at io.netty.util.internal.logging.JdkLogger.log(JdkLogger.java:606)
	  at io.netty.util.internal.logging.JdkLogger.warn(JdkLogger.java:420)
	  at io.netty.util.internal.ThreadLocalRandom.getInitialSeedUniquifier(ThreadLocalRandom.java:111)
	  - locked <0xcf3> (a java.lang.Class)
	  at io.netty.util.internal.ThreadLocalRandom.newSeed(ThreadLocalRandom.java:162)
	  at io.netty.util.internal.ThreadLocalRandom.<init>(ThreadLocalRandom.java:205)
	  at io.netty.util.internal.InternalThreadLocalMap.random(InternalThreadLocalMap.java:217)
	  at io.netty.util.internal.ThreadLocalRandom.current(ThreadLocalRandom.java:215)
	  at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:57)
	  at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:82)
	  at io.netty.channel.nio.AbstractNioByteChannel.<init>(AbstractNioByteChannel.java:52)
	  at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:96)
	  at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:86)
	  at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:72)
	  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java:-1)
	  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	  at java.lang.Class.newInstance(Class.java:442)
	  at io.netty.bootstrap.AbstractBootstrap$BootstrapChannelFactory.newChannel(AbstractBootstrap.java:454)
	  at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:307)
	  at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:135)
	  at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:117)
	  at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:98)
	  at org.eclipse.milo.opcua.stack.client.UaTcpStackClient.bootstrap(UaTcpStackClient.java:373)
	  at org.eclipse.milo.opcua.stack.client.ClientChannelManager.connect(ClientChannelManager.java:190)
	  at org.eclipse.milo.opcua.stack.client.ClientChannelManager.getChannel(ClientChannelManager.java:64)
	  at org.eclipse.milo.opcua.stack.client.UaTcpStackClient.sendRequest(UaTcpStackClient.java:126)
	  at org.eclipse.milo.opcua.stack.client.UaTcpStackClient.getEndpoints(UaTcpStackClient.java:430)
	  at edu.kit.pse.osip.core.opcua.client.UAClientWrapper.createClient(UAClientWrapper.java:110)
	  at edu.kit.pse.osip.core.opcua.client.UAClientWrapper.connectClient(UAClientWrapper.java:154)
	  at edu.kit.pse.osip.monitoring.controller.MonitoringController.setupClients(MonitoringController.java:189)
	  at edu.kit.pse.osip.monitoring.controller.MonitoringController.start(MonitoringController.java:108)
	  at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	  at com.sun.javafx.application.LauncherImpl$$Lambda$168.1725786102.run(Unknown Source:-1)
	  at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	  at com.sun.javafx.application.PlatformImpl$$Lambda$52.1777513422.run(Unknown Source:-1)
	  at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	  at com.sun.javafx.application.PlatformImpl$$Lambda$55.755445657.run(Unknown Source:-1)
	  at java.security.AccessController.doPrivileged(AccessController.java:-1)
	  at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	  at com.sun.javafx.application.PlatformImpl$$Lambda$53.1551519769.run(Unknown Source:-1)
	  at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	  at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java:-1)
	  at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	  at com.sun.glass.ui.gtk.GtkApplication$$Lambda$43.2033631737.run(Unknown Source:-1)
	  at java.lang.Thread.run(Thread.java:745)
```

**Comment by ByteHamster** [comment]
`print(buf[i]);` in `write()` ruft `print(int i)` auf, statt `print(char c)`. Die Ausgabe sind also character codes, die nicht in chars übersetzt wurden!!
