### ISSUE TITLE
Deadlock beim Restart

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#453]
Manchmal funktioniert der Reset nicht: Das Programm hängt sich bei `stepTimer.cancel();` in `startMainLoop()` auf.

**Comment by ByteHamster** [comment]
Okay das tritt auch manchmal beim Verschieben der Regler im control fenster auf. Ist also kein Problem von `startMainLoop`. Sorgt dafür, dass der desktop manager unbenutzbar wird, bis man in tty2 den Prozess beendet. JavaFX Fehler oder OSIP?

**Comment by ByteHamster** [comment]
```
"JavaFX Application Thread@806" prio=5 tid=0x11 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 blocks Timer-5@4428
	 waiting for Timer-5@4428 to release lock on <0x114d> (a edu.kit.pse.osip.core.model.base.Pipe)
	  at edu.kit.pse.osip.core.model.base.Pipe.getValveThreshold(Pipe.java:81)
	  at edu.kit.pse.osip.simulation.controller.SimulationController.updateServerValues(SimulationController.java:244)
```
mit
```
"Timer-5@4428" daemon prio=5 tid=0x34 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 blocks JavaFX Application Thread@806
	 waiting for JavaFX Application Thread@806 to release lock on <0x114e> (a edu.kit.pse.osip.core.model.base.Pipe)
	  at edu.kit.pse.osip.core.model.base.Pipe.getValveThreshold(Pipe.java:81)
	  at edu.kit.pse.osip.simulation.view.control.AbstractTankTab.update(AbstractTankTab.java:124)
	  at edu.kit.pse.osip.simulation.view.control.TankTab.update(TankTab.java:182)
```

**Comment by ByteHamster** [comment]
Sieht so aus als würden die regler Events in beide Richtungen gehen. Regler wird verschoben, löst Änderung im Model aus, Änderung setzt Regler. Zyklus und Deadlock.
